#!/bin/bash

if command -v cmake > /dev/null
then
    echo Creating makefiles
    echo

    git submodule init
    git submodule update
    mkdir bin 2>/dev/null
    cd bin
    cmake ..

    echo
    echo Compiling tests
    echo
    make Test-Poco
    make Test-Mongoose

    exit 0
else
    echo 'CMake is not available'
    echo 'Install CMake and try again'
    exit 1
fi
