#!/bin/bash


echo Creating XCode project
echo

git submodule init
git submodule update
mkdir bin 2>/dev/null
cd bin
cmake -G Xcode ..


echo
echo Launching XCode...
echo
open -a XCode SpeedTest.xcodeproj --args -license
